FROM node:20-bullseye as build

WORKDIR /app
COPY package*.json ./

RUN apt-get update && apt-get install -y build-essential python3 g++ cmake

RUN npm ci --production=false

COPY . .
RUN npm run build

FROM node:20-bullseye-slim
WORKDIR /app

COPY --from=build /app ./
ENV NODE_ENV=production

EXPOSE 4000
CMD ["node", "dist/server.js"]
